# Generated by Django 3.2.11 on 2022-01-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Cognome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('Dta_di_nascita', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
